for building debian packages

diff --git a/debian/ukui-kwin-wayland.postinst b/debian/ukui-kwin-wayland.postinst
--- a/debian/ukui-kwin-wayland.postinst
+++ b/debian/ukui-kwin-wayland.postinst
@@ -6,10 +6,10 @@ if [ "$1" = configure ]; then
     # Set the capabilities
     if command -v setcap > /dev/null && \
        setcap "CAP_SYS_RESOURCE=+ep" \
-            /usr/bin/ukwm2_wayland; then
-        echo "Sucessfully set capabilities for ukwm2_wayland"
+            /usr/bin/kwin_wayland; then
+        echo "Sucessfully set capabilities for ukui-kwin_wayland"
     else
-        echo "Failed to set capabilities for ukwm2_wayland" >&2
+        echo "Failed to set capabilities for ukui-kwin_wayland" >&2
     fi
 fi
 
